/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Consultas.cons_fac;
import Consultas.cons_ped;
import Generales.Metodos;
import LOGIN.logeo;
import static LOGIN.logeo.modlog;
import Mantenimiento.Mant_Cli;
import Mantenimiento.Mant_Emp;
import Mantenimiento.Mant_Pro;
import Utilidades.BACKUP;
import Utilidades.Mant_user;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import  javax.swing.*;
/**
 *
 * @author paul
 */
public class Menu extends javax.swing.JFrame {

  Metodos oMet = new Metodos();
           
    public Menu() {
        initComponents();
        modiniciado();
        this.setLocationRelativeTo(null);
    }
    
    private void modiniciado(){
        int x= Integer.parseInt(oMet.Datos("usuario", "idT_user", "usu", logeo.txtusu.getText()));
        String z;
       
     
        if(x==1){
            z="admin";
        }else{
            z="users";
        }
      lblmodini.setText("Iniciado como: "+z);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon= new ImageIcon(getClass().getResource("/Recursos/imagen1.jpg"));
        Image image=icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent (Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }};
            lblmodini = new javax.swing.JLabel();
            jMenuBar1 = new javax.swing.JMenuBar();
            jMenu1 = new javax.swing.JMenu();
            jMenuItem1 = new javax.swing.JMenuItem();
            jMenuItem10 = new javax.swing.JMenuItem();
            jMenuItem11 = new javax.swing.JMenuItem();
            jMenuItem2 = new javax.swing.JMenuItem();
            jMenu2 = new javax.swing.JMenu();
            jMenuItem3 = new javax.swing.JMenuItem();
            jMenuItem4 = new javax.swing.JMenuItem();
            jMenuItem5 = new javax.swing.JMenuItem();
            jMenu3 = new javax.swing.JMenu();
            jMenuItem6 = new javax.swing.JMenuItem();
            jMenuItem7 = new javax.swing.JMenuItem();
            jMenuItem12 = new javax.swing.JMenuItem();
            jMenu4 = new javax.swing.JMenu();
            jMenuItem8 = new javax.swing.JMenuItem();
            jMenuItem9 = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            lblmodini.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
            lblmodini.setForeground(new java.awt.Color(255, 255, 51));

            jDesktopPane1.setLayer(lblmodini, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
            jDesktopPane1.setLayout(jDesktopPane1Layout);
            jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(249, Short.MAX_VALUE)
                    .addComponent(lblmodini, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23))
            );
            jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(221, Short.MAX_VALUE)
                    .addComponent(lblmodini, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20))
            );

            jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/003-carpetas.png"))); // NOI18N
            jMenu1.setText("Archivo");

            jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/013-cancelar.png"))); // NOI18N
            jMenuItem1.setText("Cerrar Sesion");
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem1);

            jMenuItem10.setText("Crear Cuenta");
            jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem10ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem10);

            jMenuItem11.setText("Crear Backup");
            jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem11ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem11);

            jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/012-logout.png"))); // NOI18N
            jMenuItem2.setText("Salir");
            jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem2);

            jMenuBar1.add(jMenu1);

            jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/010-engranajes.png"))); // NOI18N
            jMenu2.setText("Mantenimientos");

            jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/011-personas.png"))); // NOI18N
            jMenuItem3.setText("Mant Clientes");
            jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem3ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem3);

            jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/009-controlar.png"))); // NOI18N
            jMenuItem4.setText("Mant Productos");
            jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem4ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem4);

            jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/img6.jpg"))); // NOI18N
            jMenuItem5.setText("Mant Empleados");
            jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem5ActionPerformed(evt);
                }
            });
            jMenu2.add(jMenuItem5);

            jMenuBar1.add(jMenu2);

            jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Movimiento.png"))); // NOI18N
            jMenu3.setText("Movimientos");

            jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/001-estudiante-en-la-computadora.png"))); // NOI18N
            jMenuItem6.setText("Pedidos");
            jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem6ActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuItem6);

            jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/003-contrato.png"))); // NOI18N
            jMenuItem7.setText("Facturas");
            jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem7ActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuItem7);

            jMenuItem12.setText("Proforma");
            jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem12ActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuItem12);

            jMenuBar1.add(jMenu3);

            jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Consultas.png"))); // NOI18N
            jMenu4.setText("Consultas");

            jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/006-lista.png"))); // NOI18N
            jMenuItem8.setText("Pedidos");
            jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem8ActionPerformed(evt);
                }
            });
            jMenu4.add(jMenuItem8);

            jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/008-bloc.png"))); // NOI18N
            jMenuItem9.setText("Facturas");
            jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem9ActionPerformed(evt);
                }
            });
            jMenu4.add(jMenuItem9);

            jMenuBar1.add(jMenu4);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       Pedidos p = new Pedidos();
       p.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int fx= JOptionPane.showConfirmDialog(this, "Seguro que desea cerrar el programa");
       if(fx==0){
              System.exit(0);
       } 
     
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Facturas f = new Facturas();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       cons_ped pc= new cons_ped();
       pc.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       Mant_Cli mc= new Mant_Cli();
       mc.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       Mant_Emp me= new Mant_Emp();
       me.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      Mant_Pro mp = new Mant_Pro();
      mp.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
      cons_fac cf= new cons_fac();
      cf.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     dispose();
     logeo log = new logeo();
     log.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
      String ss = lblmodini.getText().substring(14, 20).trim();
     
       if("admin".equalsIgnoreCase(ss)){
           Mant_user mu= new Mant_user();
           mu.setVisible(true);
       }else{
           JOptionPane.showMessageDialog(null, "Ud. no tiene privilegios para realizar esa accion");
       }
       
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
           String ss = lblmodini.getText().substring(14, 20).trim();
     
       if("admin".equalsIgnoreCase(ss)){
           BACKUP bu= new BACKUP();
           bu.setVisible(true);
       }else{
           JOptionPane.showMessageDialog(null, "Ud. no tiene privilegios para realizar esa accion");
       }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        Proforma p = new Proforma();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel lblmodini;
    // End of variables declaration//GEN-END:variables
}
